using UIKit;
using Foundation;
using System;

namespace MasDev.iOS.Utils
{
	public static class ApplicationUtils
	{
		private static string libraryFolderPath;

		// Lirabry is a good place to store files not directly generated by the user
		public static string LibraryFolderPath
		{
			get 
			{
				if (string.IsNullOrEmpty (libraryFolderPath))
				{
					string docFolder = string.Empty;
					if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
						docFolder = NSFileManager.DefaultManager.GetUrls(NSSearchPathDirectory.DocumentDirectory, NSSearchPathDomain.User) [0].Path;
					else
						docFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal); // Documents folder

					libraryFolderPath = System.IO.Path.Combine(docFolder, "..", "Library"); // Library folder instead 
				}

				return libraryFolderPath;
			}
		}

		public static bool DeviceIsTablet {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Pad; }
		}

		public static void DisableScreenLock(bool disabled)
		{
			UIApplication.SharedApplication.IdleTimerDisabled = disabled;
		}

		public static void ShowNetworkActivityIndicator(bool visible)
		{
			UIApplication.SharedApplication.NetworkActivityIndicatorVisible = visible;
		}
	}
}